[2021-01-15 21:39:10,080][WARN ][background-preinit] For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath (CompositeLog.java:127)
[2021-01-15 21:39:13,783][WARN ][main] [net.lab1024.smartadmin.module.business.email.EmailDao.deleteById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.DeleteById] (AbstractMethod.java:323)
[2021-01-15 21:39:13,884][WARN ][main] [net.lab1024.smartadmin.module.business.log.userloginlog.UserLoginLogDao.deleteById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.DeleteById] (AbstractMethod.java:323)
[2021-01-15 21:39:13,932][WARN ][main] [net.lab1024.smartadmin.module.business.log.useroperatelog.UserOperateLogDao.deleteById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.DeleteById] (AbstractMethod.java:323)
[2021-01-15 21:39:14,062][WARN ][main] [net.lab1024.smartadmin.module.business.peony.dao.PeonyDao.deleteById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.DeleteById] (AbstractMethod.java:323)
[2021-01-15 21:39:14,244][WARN ][main] Warn: Could not find @TableId in Class: net.lab1024.smartadmin.module.support.smartreload.domain.entity.ReloadResultEntity. (TableInfoHelper.java:296)
[2021-01-15 21:39:24,769][WARN ][smartreload-1-thread-1] <<SmartReload>> <<system_config>> , args 234 reload success  (SystemConfigService.java:73)
[2021-01-15 22:09:19,226][WARN ][QuartzScheduler_devClusteredScheduler-lihaifengdeMacBook-Pro.local1610717955240_MisfireHandler] Failed to override connection auto commit/transaction isolation. (JobStoreCMT.java:198)
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 315,134 milliseconds ago. The last packet sent successfully to the server was 315,159 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2056) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.p6spy.engine.wrapper.ConnectionWrapper.setAutoCommit(ConnectionWrapper.java:217) ~[p6spy-3.9.1.jar:?]
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:738) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:986) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:733) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:986) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:733) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.setAutoCommit(ConnectionProxyImpl.java:429) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.pool.DruidPooledConnection.setAutoCommit(DruidPooledConnection.java:713) ~[druid-1.1.21.jar:1.1.21]
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.setAutoCommit(AttributeRestoringConnectionInvocationHandler.java:98) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:66) ~[quartz-2.3.2.jar:?]
	at com.sun.proxy.$Proxy253.setAutoCommit(Unknown Source) ~[?:?]
	at org.quartz.impl.jdbcjobstore.JobStoreCMT.getNonManagedTXConnection(JobStoreCMT.java:191) [quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3246) [quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012) [quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033) [quartz-2.3.2.jar:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 315,134 milliseconds ago. The last packet sent successfully to the server was 315,159 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.clearInputStream(NativeProtocol.java:808) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:623) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:941) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:887) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1073) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2046) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	... 15 more
Caused by: java.io.IOException: Socket is closed
	at com.mysql.cj.protocol.AbstractSocketConnection.getMysqlInput(AbstractSocketConnection.java:72) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.clearInputStream(NativeProtocol.java:804) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:623) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:941) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:887) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1073) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2046) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	... 15 more
[2021-01-15 22:12:30,069][WARN ][SpringContextShutdownHook] close connection error (DruidDataSource.java:2050)
java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1848) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1705) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:721) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.p6spy.engine.wrapper.ConnectionWrapper.close(ConnectionWrapper.java:236) ~[p6spy-3.9.1.jar:?]
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:186) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.stat.StatFilter.connection_close(StatFilter.java:261) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:181) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.stat.StatFilter.connection_close(StatFilter.java:261) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:181) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.close(ConnectionProxyImpl.java:114) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.pool.DruidDataSource.close(DruidDataSource.java:2048) [druid-1.1.21.jar:1.1.21]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:339) [spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:273) [spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571) [spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543) [spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1072) [spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504) [spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1065) [spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060) [spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1029) [spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948) [spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
[2021-01-15 22:12:33,155][WARN ][background-preinit] For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath (CompositeLog.java:127)
[2021-01-15 22:12:36,874][WARN ][main] [net.lab1024.smartadmin.module.business.email.EmailDao.deleteById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.DeleteById] (AbstractMethod.java:323)
[2021-01-15 22:12:36,977][WARN ][main] [net.lab1024.smartadmin.module.business.log.userloginlog.UserLoginLogDao.deleteById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.DeleteById] (AbstractMethod.java:323)
[2021-01-15 22:12:37,025][WARN ][main] [net.lab1024.smartadmin.module.business.log.useroperatelog.UserOperateLogDao.deleteById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.DeleteById] (AbstractMethod.java:323)
[2021-01-15 22:12:37,166][WARN ][main] [net.lab1024.smartadmin.module.business.peony.dao.PeonyDao.deleteById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.DeleteById] (AbstractMethod.java:323)
[2021-01-15 22:12:37,355][WARN ][main] Warn: Could not find @TableId in Class: net.lab1024.smartadmin.module.support.smartreload.domain.entity.ReloadResultEntity. (TableInfoHelper.java:296)
[2021-01-15 22:12:47,889][WARN ][smartreload-1-thread-1] <<SmartReload>> <<system_config>> , args 234 reload success  (SystemConfigService.java:73)
[2021-01-15 22:42:26,466][WARN ][devClusteredScheduler_QuartzSchedulerThread] Failed to override connection auto commit/transaction isolation. (JobStoreCMT.java:198)
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 273,659 milliseconds ago. The last packet sent successfully to the server was 273,685 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2056) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.p6spy.engine.wrapper.ConnectionWrapper.setAutoCommit(ConnectionWrapper.java:217) ~[p6spy-3.9.1.jar:?]
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:738) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:986) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:733) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:986) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:733) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.setAutoCommit(ConnectionProxyImpl.java:429) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.pool.DruidPooledConnection.setAutoCommit(DruidPooledConnection.java:713) ~[druid-1.1.21.jar:1.1.21]
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.setAutoCommit(AttributeRestoringConnectionInvocationHandler.java:98) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:66) ~[quartz-2.3.2.jar:?]
	at com.sun.proxy.$Proxy253.setAutoCommit(Unknown Source) ~[?:?]
	at org.quartz.impl.jdbcjobstore.JobStoreCMT.getNonManagedTXConnection(JobStoreCMT.java:191) [quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3861) [quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802) [quartz-2.3.2.jar:?]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287) [quartz-2.3.2.jar:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 273,659 milliseconds ago. The last packet sent successfully to the server was 273,685 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.clearInputStream(NativeProtocol.java:808) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:623) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:941) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:887) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1073) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2046) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	... 15 more
Caused by: java.io.IOException: Socket is closed
	at com.mysql.cj.protocol.AbstractSocketConnection.getMysqlInput(AbstractSocketConnection.java:72) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.clearInputStream(NativeProtocol.java:804) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:623) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:941) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:887) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1073) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2046) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	... 15 more
[2021-01-15 22:43:07,512][WARN ][LogAspect pool 1-thread-1] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 22:44:22,934][WARN ][LogAspect pool 1-thread-2] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 22:44:40,848][WARN ][LogAspect pool 1-thread-3] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 22:50:28,685][WARN ][LogAspect pool 1-thread-4] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 22:51:24,178][WARN ][LogAspect pool 1-thread-5] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 22:53:40,199][WARN ][LogAspect pool 1-thread-6] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:01:06,183][WARN ][LogAspect pool 1-thread-7] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:06:06,033][WARN ][LogAspect pool 1-thread-8] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:08:09,213][WARN ][LogAspect pool 1-thread-9] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:08:33,349][WARN ][LogAspect pool 1-thread-10] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:09:39,048][WARN ][LogAspect pool 1-thread-11] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:13:22,169][WARN ][LogAspect pool 1-thread-12] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:15:55,539][WARN ][LogAspect pool 1-thread-13] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:18:34,935][WARN ][LogAspect pool 1-thread-14] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:24:53,716][WARN ][LogAspect pool 1-thread-15] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:30:36,945][WARN ][LogAspect pool 1-thread-16] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:33:09,058][WARN ][LogAspect pool 1-thread-17] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:37:57,888][WARN ][LogAspect pool 1-thread-18] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:39:35,127][WARN ][LogAspect pool 1-thread-19] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:40:42,193][WARN ][LogAspect pool 1-thread-20] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:41:25,538][WARN ][LogAspect pool 1-thread-21] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:41:46,782][WARN ][LogAspect pool 1-thread-22] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:42:12,651][WARN ][LogAspect pool 1-thread-23] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:43:41,115][WARN ][LogAspect pool 1-thread-24] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:44:00,599][WARN ][LogAspect pool 1-thread-25] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
[2021-01-15 23:44:26,918][WARN ][LogAspect pool 1-thread-26] Unexpected exception on closing transaction.  Cause: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown. (BaseExecutor.java:95)
